version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - ms-launcher/target/ms-launcher-1.0-SNAPSHOT.jar
  discard-paths: yes
